name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'diana_landing/**'
      - '.github/workflows/deploy-landing.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload landing page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'diana_landing'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
