name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'diana_frontend/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: diana_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: diana_frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NEXT_EXPORT: 'true'
          NEXT_PUBLIC_BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build
          npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: diana_frontend/out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

