name: Deploy Landing + Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'diana_frontend/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: diana_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: diana_frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build Next.js export (served under /app)
        env:
          NEXT_EXPORT: 'true'
          # Pages hosts at /<repo>, we serve Next app at /<repo>/app
          NEXT_PUBLIC_BASE_PATH: '/${{ github.event.repository.name }}/app'
        run: |
          npm run build
          npm run export

      - name: Assemble Pages artifact (landing at root, Next at /app)
        run: |
          mkdir -p ../pages-dist
          cp -R ../diana_landing/* ../pages-dist/
          mkdir -p ../pages-dist/app
          cp -R out/* ../pages-dist/app/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages-dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

